### ISSUE TITLE
AttributeError: module 'phobos.utils.blender' has no attribute 'defLayers'

### ISSUE THREAD

**Issue by hetolin** [dfki-ric/phobos#219]
**Describe the bug**
when I import a urdf file, it throw the error:
`
Python: Traceback (most recent call last):
  File "/home/hetolin/.config/blender/2.91/scripts/addons/phobos/operators/io.py", line 283, in execute
    models.buildModelFromDictionary(model)
  File "/home/hetolin/.config/blender/2.91/scripts/addons/phobos/model/models.py", line 1208, in buildModelFromDictionary
    model['links'][lnk]['object'] = linkmodel.createLink(link)
  File "/home/hetolin/.config/blender/2.91/scripts/addons/phobos/model/links.py", line 125, in createLink
    geometrymodel.createGeometry(vis, 'visual', newlink)
  File "/home/hetolin/.config/blender/2.91/scripts/addons/phobos/model/geometries.py", line 150, in createGeometry
    bpy.context.scene.layers = bUtils.defLayers(defs.layerTypes[geomsrc])
AttributeError: module 'phobos.utils.blender' has no attribute 'defLayers'
location: <unknown location>:-1
`
**To Reproduce**
1. Go to 'Phobos' add-on button
2. Click on 'Import robot Model'
3. Choose 'Entity type: urdf'
4. Choose my `urdf` file
5.  See error

**Expected behavior**
import a urdf model in the Blender

**Desktop (please complete the following information):**
 - OS Version: `Ubuntu 16.04`
 - Blender Version: `2.91`
 - Phobos Version: `branch 2.9`

**Comment by malter** [comment]
The error should be fixed now. At least, except for Materials, a small test URDF imported correctly.
