### ISSUE TITLE
Error on "Name Model"

### ISSUE THREAD

**Issue by Aiacos** [dfki-ric/phobos#220]
**Describe the bug**
When I click on "Name Model" I have this message error:
Traceback (most recent call last):
  File "/home/aiacos/.config/blender/2.79/scripts/addons/phobos/operators/naming.py", line 120, in execute
    root.pose.bones[0].custom_shape = ioUtils.getResource(('link', 'root'))
  File "/home/aiacos/.config/blender/2.79/scripts/addons/phobos/utils/io.py", line 416, in getResource
    newobjects = importResources((specifiers,))
  File "/home/aiacos/.config/blender/2.79/scripts/addons/phobos/utils/io.py", line 386, in importResources
    with bpy.data.libraries.load(filepath) as (data_from, data_to):
OSError: load: /home/aiacos/hexapod_ws/config/resources/resources.blend failed to open blend file

location: <unknown location>:-1

Unable to validate and export

**Additional context**
phobos v1.0 on Ubuntu 20.04 LTS

**Comment by malter** [comment]
Fixed on blender2.9 branch
