### ISSUE TITLE
Error when loading urdf file for robot hands

### ISSUE THREAD

**Issue by YoruCathy** [dfki-ric/phobos#226]
**Describe the bug**
When loading URDF, the mesh parts are loaded but in a messy order, and the code returns errors and warnings.

**To Reproduce**
1. Install and activate phobos add-on
2. run`bpy.ops.phobos.import_robot_model(filepath="D:/robot/hand_models/dh3_urdf/urdf/dh3_urdf.urdf")`in scriptting

**Screenshots**
The robot hand becomes like this after urdf is loaded, which is not the right structure.
![image](https://user-images.githubusercontent.com/16759982/122944858-bc2e8b00-d3aa-11eb-8f11-3bc20c1a31b3.png)

![image](https://user-images.githubusercontent.com/16759982/122945832-6f977f80-d3ab-11eb-9fe8-688ffd5d8947.png)

**Desktop:**
- OS: Win10
- Blender version 2.93
- I use Phobos in this branch: https://github.com/dfki-ric/phobos/tree/blender2.9

**Additional context**
Errorlog:
[20210622_22:42:20] [1m[91mERROR[0m Can not create inertial object.[2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\inertia.py - createInertial (l49))[0m
[20210622_22:42:20] [1m[91mERROR[0m This path D:\robot\hand_correspondance\hand_models\dh3_urdf\urdf\package:\dh3_urdf\meshes\base_Link.STL is no file. Object visual_0_base_Link will have empty mesh![2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\geometries.py - createGeometry (l153))[0m
[20210622_22:42:20] [1m[91mERROR[0m Material '' is not defined.[2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\materials.py - assignMaterial (l115))[0m
[20210622_22:42:20] [1m[91mERROR[0m This path D:\robot\hand_correspondance\hand_models\dh3_urdf\urdf\package:\dh3_urdf\meshes\base_Link.STL is no file. Object collision_0_base_Link will have empty mesh![2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\geometries.py - createGeometry (l153))[0m
[20210622_22:42:20] [1m[91mERROR[0m Can not create inertial object.[2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\inertia.py - createInertial (l49))[0m
[20210622_22:42:20] [1m[91mERROR[0m This path D:\robot\hand_correspondance\hand_models\dh3_urdf\urdf\package:\dh3_urdf\meshes\finger1_base_Link.STL is no file. Object visual_0_finger1_base_Link will have empty mesh![2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\geometries.py - createGeometry (l153))[0m
[20210622_22:42:20] [1m[91mERROR[0m Material '' is not defined.[2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\materials.py - assignMaterial (l115))[0m
[20210622_22:42:20] [1m[91mERROR[0m This path D:\robot\hand_correspondance\hand_models\dh3_urdf\urdf\package:\dh3_urdf\meshes\finger1_base_Link.STL is no file. Object collision_0_finger1_base_Link will have empty mesh![2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\geometries.py - createGeometry (l153))[0m
[20210622_22:42:20] [1m[91mERROR[0m Can not create inertial object.[2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\inertia.py - createInertial (l49))[0m
[20210622_22:42:20] [1m[91mERROR[0m This path D:\robot\hand_correspondance\hand_models\dh3_urdf\urdf\package:\dh3_urdf\meshes\finger1_Link.STL is no file. Object visual_0_finger1_Link will have empty mesh![2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\geometries.py - createGeometry (l153))[0m
[20210622_22:42:20] [1m[91mERROR[0m Material '' is not defined.[2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\materials.py - assignMaterial (l115))[0m
[20210622_22:42:20] [1m[91mERROR[0m This path D:\robot\hand_correspondance\hand_models\dh3_urdf\urdf\package:\dh3_urdf\meshes\finger1_Link.STL is no file. Object collision_0_finger1_Link will have empty mesh![2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\geometries.py - createGeometry (l153))[0m
[20210622_22:42:20] [1m[91mERROR[0m Can not create inertial object.[2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\inertia.py - createInertial (l49))[0m
[20210622_22:42:20] [1m[91mERROR[0m This path D:\robot\hand_correspondance\hand_models\dh3_urdf\urdf\package:\dh3_urdf\meshes\finger1_tip_Link.STL is no file. Object visual_0_finger1_tip_Link will have empty mesh![2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\geometries.py - createGeometry (l153))[0m
[20210622_22:42:20] [1m[91mERROR[0m Material '' is not defined.[2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\materials.py - assignMaterial (l115))[0m
[20210622_22:42:20] [1m[91mERROR[0m This path D:\robot\hand_correspondance\hand_models\dh3_urdf\urdf\package:\dh3_urdf\meshes\finger1_tip_Link.STL is no file. Object collision_0_finger1_tip_Link will have empty mesh![2m (C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\geometries.py - createGeometry (l153))[0m

Error: Python: Traceback (most recent call last):
  File "C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\operators\io.py", line 285, in execute
    models.buildModelFromDictionary(model)
  File "C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\models.py", line 1306, in buildModelFromDictionary
    bpy.ops.view3d.view_selected()
  File "D:\blender\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.view3d.view_selected.poll() expected a view3d region

location: D:\blender\2.93\scripts\modules\bpy\ops.py:132

Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "D:\blender\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\operators\io.py", line 285, in execute
    models.buildModelFromDictionary(model)
  File "C:\Users\cathy\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\phobos\model\models.py", line 1306, in buildModelFromDictionary
    bpy.ops.view3d.view_selected()
  File "D:\blender\2.93\scripts\modules\bpy\ops.py", line 132, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.view3d.view_selected.poll() expected a view3d region

location: D:\blender\2.93\scripts\modules\bpy\ops.py:132

**Comment by malter** [comment]
Hey, I just checked the URDF import on Windows10 with Blender 2.93 with a rather complex model and it was working fine. Could you share your model or another small one that is not working on your system? Once I can reproduce the problem I might be able to fix it. ;-)

**Comment by YoruCathy** [comment]
Great! I put the urdf in google drive. 
https://drive.google.com/drive/folders/1pjpMU0irj_YzmC95j279X1DfiNXLYFjd?usp=sharing

**Comment by malter** [comment]
Thank you for the model. Unfortunately, Phobos can not deal with `package://` file path from ROS. So if you replace "package://dh3_urdf/" with the relative path "../" in the URDF file the model should load fine. I don't yet have a clue how to deal with the url correctly. Something like searching the package root by searching for the `package.xml`?

**Comment by YoruCathy** [comment]
Oh, I see, that is a problem. I tried to replace the 'package://' with the path the mesh files are, but that will also cause some errors. 
For example, the shadowhand model, I replaced the path, and loaded it. 
![image](https://user-images.githubusercontent.com/16759982/123053357-630c3900-d436-11eb-9092-efa021864cc8.png)

![image](https://user-images.githubusercontent.com/16759982/123053441-78816300-d436-11eb-8fc5-94a21c9ba769.png)
I think the inertial should not affect visualization, but the mesh is still messy.
![image](https://user-images.githubusercontent.com/16759982/123053479-83d48e80-d436-11eb-9145-a099196a617c.png)
Can you load the shadowhand model correctly?

**Comment by malter** [comment]
Ok, here you found the next issue ;-)
Phobos is not importing the mesh scale correctly, maybe due to the adaptations to the new Blender version. So I had to scale down all meshes by a factor of `0.1`. Also the DAE materials are not loaded correctly, after removing the `black_spec.00x` materials from the meshes in Blender it looks not that bad:
![Bildschirmfoto 2021-06-23 um 09 35 25](https://user-images.githubusercontent.com/7878454/123056236-fcbbf200-d406-11eb-9b2d-9cfcd8d90f75.png)
![Bildschirmfoto 2021-06-23 um 09 36 30](https://user-images.githubusercontent.com/7878454/123056261-02b1d300-d407-11eb-836e-03c68093861c.png)

**Comment by YoruCathy** [comment]
WOW yours looks awesome, but I still cannot do it. Are you adjusting the scale here? 
![image](https://user-images.githubusercontent.com/16759982/123060032-f183b900-d43c-11eb-863b-e3bc0064d154.png)

**Comment by malter** [comment]
Yes, but sorry the factor was `0.01` so changing `0.1` to `0.001`.

**Comment by YoruCathy** [comment]
It works! Thanks a lot.
