### ISSUE TITLE
Import URDF error

### ISSUE THREAD

**Issue by tomkimsour** [dfki-ric/phobos#256]
When I try importing urdf I get this error : 

```
Python: Traceback (most recent call last):
  File "/home/crossing-laptop/.config/blender/3.0/scripts/addons/phobos/operators/io.py", line 283, in execute
    model = entity_io.entity_types[suffix]['import'](self.filepath)
  File "/home/crossing-laptop/.config/blender/3.0/scripts/addons/phobos/io/entities/urdf.py", line 620, in importUrdf
    log(" Adding link {}.".format(link.attrib['name']), 'DEBUG')
KeyError: 'name'

location: <unknown location>:-1
```

**To Reproduce**
I am using blender 3.3 on ubuntu 22
To install the add on I followed the steps written in the readme of phobos.
Model path is set to where my urdf files are.
All other paths of the plugins are not set and left blank.

Then I opened the Phobos tab, clicked on import and import the urdf file.
You can find urdf [here](https://github.com/ros-naoqi/pepper_robot/blob/master/pepper_description/urdf/pepper1.0_generated_urdf/pepper.urdf)

**Expected behavior**
Import the urdf file into blender

**Screenshots**
Error I am getting
![image](https://user-images.githubusercontent.com/48397347/189045793-43c3251f-590c-490b-be9a-f43d7335eecf.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04

**Additional context**
Also I tried it on windows 10 with the same setup and files and I am getting the same error

**Comment by tomkimsour** [comment]
For anyone having similar issue. The problem was coming from my urdf file where I had gazebo values that were parsed. I just commented them out.

To find it I used a [blender addon debugger using vscode](https://github.com/alanscodelog/blender-debugger-for-vscode).
