### ISSUE TITLE
[pre_v2.0.0] Create Collision Objects by mesh

### ISSUE THREAD

**Issue by brothermechanic** [dfki-ric/phobos#278]
**Describe the bug**
Create Collision Objects by mesh don't works (any other options like cube - works)

**To Reproduce**
1. Run bpy.ops.phobos.create_collision_objects() ("Create Collision Objects")
2. Select type - Mesh
```python
Error: Python: Traceback (most recent call last):
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/operators/editing.py", line 1343, in execute
    bpy.ops.object.transform_apply(location=False, rotation=False, scale=True, properties=False)
  File "/usr/share/blender/3.5/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Cannot apply to a multi user: Object "grip_rotator_collision", Mesh "Part__Feature007.003", aborting
```

**Expected behavior**
In Phobos v1 it works

**Desktop:**
 - OS: Gentoo
 - Version: ~amd64

**Comment by brothermechanic** [comment]
@hwiedPro  Hi,
Error message has changed
```python
Python: Traceback (most recent call last):
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/operators/editing.py", line 1282, in execute
    phobos_vis = blender2phobos.deriveVisual(vis)
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/io/blender2phobos.py", line 189, in deriveVisual
    material = deriveMaterial(obj.active_material, logging=logging)
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/io/blender2phobos.py", line 50, in deriveMaterial
    if "No material defined." in errors:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by brothermechanic** [comment]
@hwiedPro  new error message

```python
Error: Python: Traceback (most recent call last):
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/operators/editing.py", line 1318, in execute
    origin=representation.Pose.from_matrix(phobos_vis.origin.to_matrix().dot(transform))
TypeError: Pose.from_matrix() missing 1 required positional argument: 'relative_to'
```

i think collision wants be relative from armature object, but can't find it

**Comment by hwiedPro** [comment]
Perfect that you have found that. To facilitate more profound SDF support I recently made the relative_to property mandatory for all Poses. I thought I had found all usages but some seem to have slipped through. I'll push the fix asap

**Comment by brothermechanic** [comment]
```ptyhon
Python: Traceback (most recent call last):
  File "/home/bm/.config/blender/3.5/scripts/addons/phobos/blender/operators/editing.py", line 1318, in execute
    origin=representation.Pose.from_matrix(phobos_vis.origin.to_matrix().dot(transform))
TypeError: Pose.from_matrix() missing 1 required positional argument: 'relative_to'
```

**Comment by brothermechanic** [comment]
Maybe I'm doing something wrong ?
https://github.com/dfki-ric/phobos/assets/3109995/d8405b2c-8b01-4fbd-a736-287859300d21
[test_model.zip](https://github.com/dfki-ric/phobos/files/11450049/test_model.zip)

**Comment by hwiedPro** [comment]
Thanks, this was a not yet handled blender color type in the color parser. Should be fixed now.

**Comment by hwiedPro** [comment]
I consider this as solved, please reopen if not.
