### ISSUE TITLE
installation problem on Blender3.4

### ISSUE THREAD

**Issue by Gerka0291** [dfki-ric/phobos#303]
Do not instal after restart on version 3.4 but on 3.3.9 it is ok

print the same issue like in first time while enable addon

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.4\3.4\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\Hasee\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\phobos\__init__.py", line 125, in register
    from . import io
  File "C:\Users\Hasee\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\phobos\io\__init__.py", line 1, in <module>
    from . import representation
  File "C:\Users\Hasee\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\phobos\io\representation.py", line 9, in <module>
    import trimesh
ModuleNotFoundError: No module named 'trimesh'

**Comment by hwiedPro** [comment]
Have you restarted Blender as stated in the instructions?

**Comment by hwiedPro** [comment]
I consider this as solved, due to inactivity. Please reopen if further help is needed.

**Comment by Developer310301** [comment]
I have the same issue mentioned before
