### ISSUE TITLE
Installing the extension error: it claims to have installed all dependencies but does not enable.

### ISSUE THREAD

**Issue by herthd** [dfki-ric/phobos#359]
After installing the extension, clicking on the enabling checkbox results in this error:

'''
Traceback (most recent call last):
File "/home/john/.config/blender/3.3/scripts/addons/phobos/__init__.py", line 143, in register
from. import io
File "/home/john/.config/blender/3.3/scripts/addons/phobos/io/__init__.py", line 1, in <module>
from. import representation
File "/home/john/.config/blender/3.3/scripts/addons/phobos/io/representation.py", line 14, in <module>
from.xml_factory import singular as singular, plural as_plural
File "/home/john/.config/blender/3.3/scripts/addons/phobos/io/xml_factory.py", line 10, in <module>
import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/snap/blender/4668/3.3/scripts/modules/addon_utils.py", line 369, in enable
mod.register()
File "/home/john/.config/blender/3.3/scripts/addons/phobos/__init__.py", line 213, in register
raise ImportWarning(installation_finished message)
ImportWarning: All Phobos requirements have been installed.
Please restart Blender to activate the Phobos add-on!
e
'''

However, after restarting blender and retrying, the extension still doesn't enable.

Reproduce on Linux 22.04.4 LTS with blender 3.3.17 installed from the snap store (author = Blender Foundation)

**Comment by herthd** [comment]
It is most likely an issue that I do not know how to use the builtin python console in blender 3.3.17 to install modules. I tried to copy the files directly to the modules folder and it didn't work. Help is greatly appreciated.

**Comment by AlpenAalAlex** [comment]
This is an error in the current release. Please install the current master
